[project]
name = "mnemonic-deliberation-dashboard"
version = "0.1.0"
description = "MDD — operationalising the Law of Mnemonic Expansion"
requires-python = ">=3.11,<3.12"
readme = "README.md"
authors = [{name="Kirstin Stevens"}]
license = {text = "CC BY-NC-SA 4.0"}
